import type { OutreachItem, Person } from "@/lib/types";

export const demoUser = {
  name: "Alex Morgan",
  firstName: "Alex",
  email: "alex@demo.twenty.so",
  initials: "AM",
  headline: "Warwick graduate · Strategy analyst · Building in climate tech",
  target: "Early-stage climate tech roles in London",
};

export const people: Person[] = [
  {
    id: "maya-patel",
    name: "Maya Patel",
    initials: "MP",
    role: "Principal",
    company: "Northline Ventures",
    location: "London, UK",
    score: 96,
    responseLikelihood: "High",
    relationship: "Shared Warwick + consulting path",
    rationale:
      "Maya made the same consulting-to-venture move you are exploring and now backs climate marketplaces. Your Warwick overlap gives you a natural, specific opening.",
    signals: ["Warwick alum", "Ex-Bain", "Climate investor", "2nd-degree path"],
    experience: [
      { company: "Northline Ventures", role: "Principal", period: "2023–Now" },
      { company: "Bain & Company", role: "Consultant", period: "2018–2023" },
    ],
    education: ["University of Warwick · Economics"],
    contact: {
      status: "verified",
      email: "maya@northline.vc",
      confidence: 98,
      source: "Company domain + mailbox verification",
      note: "Public professional address; checked 2 days ago.",
    },
    social: { linkedin: "https://www.linkedin.com" },
    tags: ["Venture", "Climate", "Warm path"],
    lastActive: "Published on climate procurement this week",
  },
  {
    id: "tom-okafor",
    name: "Tom Okafor",
    initials: "TO",
    role: "Chief of Staff",
    company: "Tern Materials",
    location: "London, UK",
    score: 93,
    responseLikelihood: "High",
    relationship: "Role transition match",
    rationale:
      "Tom moved from strategy into an operator role at a Series A climate company last year. He can give unusually current advice on the exact transition you want to make.",
    signals: ["Ex-strategy", "Series A operator", "Hiring team adjacent", "Recent career move"],
    experience: [
      { company: "Tern Materials", role: "Chief of Staff", period: "2025–Now" },
      { company: "Strategy&", role: "Senior Associate", period: "2021–2025" },
    ],
    education: ["University of Manchester · PPE"],
    contact: {
      status: "verified",
      email: "tom.okafor@ternmaterials.com",
      confidence: 96,
      source: "Company domain + mailbox verification",
      note: "Work email only. Best approached with a specific question.",
    },
    social: { linkedin: "https://www.linkedin.com" },
    tags: ["Operator", "Climate", "Strategy"],
  },
  {
    id: "elena-rossi",
    name: "Elena Rossi",
    initials: "ER",
    role: "Talent Partner",
    company: "Seedcamp",
    location: "London, UK",
    score: 91,
    responseLikelihood: "Medium",
    relationship: "Portfolio-wide hiring visibility",
    rationale:
      "Elena works across dozens of early-stage teams and regularly advises candidates entering startups. One thoughtful conversation could reveal several relevant companies, not just one role.",
    signals: ["Portfolio talent", "Climate portfolio", "Career-transition content", "London"],
    experience: [
      { company: "Seedcamp", role: "Talent Partner", period: "2022–Now" },
      { company: "Otta", role: "Talent Lead", period: "2019–2022" },
    ],
    education: ["University College London · Psychology"],
    contact: {
      status: "likely",
      email: "elena@seedcamp.com",
      confidence: 82,
      source: "Company email pattern",
      note: "Pattern match only. Review before using or contact on LinkedIn.",
    },
    social: { linkedin: "https://www.linkedin.com" },
    tags: ["Talent", "Portfolio", "Startups"],
  },
  {
    id: "samira-khan",
    name: "Samira Khan",
    initials: "SK",
    role: "Founder & CEO",
    company: "Gridwise Labs",
    location: "London, UK",
    score: 89,
    responseLikelihood: "Selective",
    relationship: "Problem-space alignment",
    rationale:
      "Gridwise is solving the procurement problem you researched at work. Samira is a high-value but time-constrained contact, so the best outreach is a concise observation rather than a request for a generic coffee.",
    signals: ["Climate founder", "Procurement thesis", "Series A", "Hiring soon"],
    experience: [
      { company: "Gridwise Labs", role: "Founder & CEO", period: "2021–Now" },
      { company: "Octopus Energy", role: "Product Lead", period: "2017–2021" },
    ],
    education: ["Imperial College London · Engineering"],
    contact: {
      status: "not_sought",
      note: "We have not surfaced a direct address. Use the public founder channel first.",
    },
    social: { linkedin: "https://www.linkedin.com", website: "https://example.com" },
    tags: ["Founder", "Climate", "High value"],
    lastActive: "Spoke at London Climate Week",
  },
  {
    id: "daniel-cho",
    name: "Daniel Cho",
    initials: "DC",
    role: "Investment Manager",
    company: "Carbon13",
    location: "Cambridge, UK",
    score: 88,
    responseLikelihood: "Medium",
    relationship: "Shared sector thesis",
    rationale:
      "Daniel focuses on commercial talent for climate ventures and has written about why consulting backgrounds translate well. Your operating project is a credible proof point.",
    signals: ["Climate venture builder", "Commercial talent", "Published thesis", "Mutual interest"],
    experience: [
      { company: "Carbon13", role: "Investment Manager", period: "2024–Now" },
      { company: "KPMG", role: "Manager", period: "2019–2024" },
    ],
    education: ["University of Cambridge · Land Economy"],
    contact: {
      status: "verified",
      email: "daniel@carbonthirteen.com",
      confidence: 94,
      source: "Public team page + verification",
      note: "Published professional address; checked this week.",
    },
    social: { linkedin: "https://www.linkedin.com" },
    tags: ["Venture builder", "Climate", "Commercial"],
  },
  {
    id: "rose-mitchell",
    name: "Rose Mitchell",
    initials: "RM",
    role: "VP Strategy",
    company: "Patchwork Energy",
    location: "London, UK",
    score: 86,
    responseLikelihood: "High",
    relationship: "Alumni introduction available",
    rationale:
      "Rose leads the function closest to your current experience. A Warwick alumni group member can introduce you, making this the warmest high-relevance path in your shortlist.",
    signals: ["Warwick alum", "Warm introduction", "Strategy leader", "Growth-stage climate"],
    experience: [
      { company: "Patchwork Energy", role: "VP Strategy", period: "2023–Now" },
      { company: "Deliveroo", role: "Strategy Director", period: "2018–2023" },
    ],
    education: ["University of Warwick · MORSE"],
    contact: {
      status: "not_sought",
      note: "A warm introduction is available, so we recommend that over direct email.",
    },
    social: { linkedin: "https://www.linkedin.com" },
    tags: ["Warm intro", "Strategy", "Scale-up"],
  },
  {
    id: "jonas-berg",
    name: "Jonas Berg",
    initials: "JB",
    role: "Product Lead",
    company: "Sylva",
    location: "Remote · Europe",
    score: 83,
    responseLikelihood: "Medium",
    relationship: "Adjacent functional move",
    rationale:
      "Jonas moved from internal strategy into product without a technical background. His path is adjacent rather than exact, but useful if you are open to product strategy roles.",
    signals: ["Strategy-to-product", "Climate software", "Non-technical PM", "Open to mentoring"],
    experience: [
      { company: "Sylva", role: "Product Lead", period: "2022–Now" },
      { company: "Maersk", role: "Strategy Manager", period: "2018–2022" },
    ],
    education: ["Copenhagen Business School · Strategy"],
    contact: {
      status: "likely",
      email: "jonas@sylva.earth",
      confidence: 79,
      source: "Company email pattern",
      note: "Unverified pattern. Prefer the public mentoring link in his profile.",
    },
    social: { linkedin: "https://www.linkedin.com" },
    tags: ["Product", "Climate software", "Mentor"],
  },
  {
    id: "nina-shah",
    name: "Nina Shah",
    initials: "NS",
    role: "Senior Associate",
    company: "Pale Blue Ventures",
    location: "London, UK",
    score: 81,
    responseLikelihood: "High",
    relationship: "Peer-level perspective",
    rationale:
      "Nina is only two years ahead of you and recently made the move, which often produces more practical advice and a higher reply rate than a senior decision-maker.",
    signals: ["Recent transition", "Peer seniority", "Climate VC", "Active writer"],
    experience: [
      { company: "Pale Blue Ventures", role: "Senior Associate", period: "2025–Now" },
      { company: "OC&C", role: "Associate", period: "2022–2025" },
    ],
    education: ["London School of Economics · Economics"],
    contact: {
      status: "verified",
      email: "nina@paleblue.vc",
      confidence: 97,
      source: "Public bio + mailbox verification",
      note: "Public professional address; checked yesterday.",
    },
    social: { linkedin: "https://www.linkedin.com" },
    tags: ["Peer", "Venture", "High response"],
  },
  {
    id: "leo-williams",
    name: "Leo Williams",
    initials: "LW",
    role: "Co-founder",
    company: "Morrow",
    location: "Bristol, UK",
    score: 78,
    responseLikelihood: "Selective",
    relationship: "Company fit, weaker personal bridge",
    rationale:
      "Morrow is an excellent company fit, but there is no clear personal bridge yet. Keep Leo on the watchlist until you can reference a launch, event, or mutual connection.",
    signals: ["Strong company fit", "Founder", "No shared path", "Watchlist"],
    experience: [
      { company: "Morrow", role: "Co-founder", period: "2022–Now" },
      { company: "Bulb", role: "Growth Lead", period: "2018–2021" },
    ],
    education: ["University of Bristol · Economics"],
    contact: {
      status: "unavailable",
      note: "No reliable professional contact found. We will not guess or surface personal data.",
    },
    social: { linkedin: "https://www.linkedin.com" },
    tags: ["Founder", "Watchlist", "Climate"],
  },
  {
    id: "iman-bello",
    name: "Iman Bello",
    initials: "IB",
    role: "Platform Manager",
    company: "Elemental Excelerator",
    location: "London, UK",
    score: 76,
    responseLikelihood: "Medium",
    relationship: "Community connector",
    rationale:
      "Iman runs European founder and talent programmes. The match is less role-specific, but she is a strong network node if your aim is to understand the ecosystem quickly.",
    signals: ["Community connector", "Talent programmes", "Climate ecosystem", "London"],
    experience: [
      { company: "Elemental Excelerator", role: "Platform Manager", period: "2024–Now" },
      { company: "Tech Nation", role: "Programme Lead", period: "2020–2024" },
    ],
    education: ["SOAS University of London · Development Studies"],
    contact: {
      status: "verified",
      email: "iman@elementalexcelerator.com",
      confidence: 92,
      source: "Public programme page",
      note: "Public role-based address; checked this month.",
    },
    social: { linkedin: "https://www.linkedin.com" },
    tags: ["Community", "Connector", "Programs"],
  },
  {
    id: "henry-wu",
    name: "Henry Wu",
    initials: "HW",
    role: "Strategy Director",
    company: "Aira",
    location: "London, UK",
    score: 73,
    responseLikelihood: "Medium",
    relationship: "Functional relevance",
    rationale:
      "Henry leads strategy at a later-stage climate company. Useful for role calibration, though his path and company stage are less directly aligned with your early-stage goal.",
    signals: ["Strategy leader", "Climate scale-up", "London", "Later stage"],
    experience: [
      { company: "Aira", role: "Strategy Director", period: "2023–Now" },
      { company: "Amazon", role: "Senior Manager", period: "2017–2023" },
    ],
    education: ["Oxford University · Engineering"],
    contact: {
      status: "likely",
      email: "henry.wu@aira.com",
      confidence: 74,
      source: "Company email pattern",
      note: "Pattern match only. Verify before any contact.",
    },
    social: { linkedin: "https://www.linkedin.com" },
    tags: ["Strategy", "Scale-up", "Climate"],
  },
  {
    id: "becca-jones",
    name: "Becca Jones",
    initials: "BJ",
    role: "Independent Recruiter",
    company: "Climate Operators",
    location: "London, UK",
    score: 71,
    responseLikelihood: "High",
    relationship: "Market visibility",
    rationale:
      "Becca recruits commercial climate roles and is likely to reply, but the relationship is transactional. Contact her after your narrative and target list are sharper.",
    signals: ["Climate recruiter", "Commercial roles", "High response", "Transactional"],
    experience: [
      { company: "Climate Operators", role: "Independent Recruiter", period: "2022–Now" },
      { company: "Hays", role: "Consultant", period: "2018–2022" },
    ],
    education: ["University of Leeds · Business"],
    contact: {
      status: "verified",
      email: "becca@climateoperators.co",
      confidence: 99,
      source: "Public business address",
      note: "Published professional address.",
    },
    social: { linkedin: "https://www.linkedin.com" },
    tags: ["Recruiter", "Commercial", "High response"],
  },
];

export const outreach: OutreachItem[] = [
  {
    id: "out-1",
    personId: "maya-patel",
    subject: "A Warwick perspective on moving from consulting into climate VC",
    status: "replied",
    sentAt: "12 Aug · 09:42",
    nextStep: "Call booked · Fri, 11:00",
    updatedAt: "Today, 08:26",
  },
  {
    id: "out-2",
    personId: "tom-okafor",
    subject: "Your move from Strategy& to Tern Materials",
    status: "sent",
    sentAt: "18 Aug · 14:15",
    nextStep: "Follow up in 5 days",
    updatedAt: "Yesterday, 14:15",
  },
  {
    id: "out-3",
    personId: "elena-rossi",
    subject: "A question on early-stage climate operator roles",
    status: "follow_up",
    sentAt: "11 Aug · 10:06",
    nextStep: "Follow-up ready for review",
    updatedAt: "Today, 09:10",
  },
  {
    id: "out-4",
    personId: "nina-shah",
    subject: "Your recent move into climate investing",
    status: "scheduled",
    nextStep: "Scheduled · Thu, 08:45",
    updatedAt: "Yesterday, 17:30",
  },
  {
    id: "out-5",
    personId: "daniel-cho",
    subject: "From consulting to commercial climate work",
    status: "draft",
    nextStep: "Personalise opening line",
    updatedAt: "Mon, 16:22",
  },
];

export const weeklyActivity = [4, 7, 5, 9, 11, 8, 13, 16, 12, 18, 14, 20];

export function getPerson(id: string) {
  return people.find((person) => person.id === id);
}

export function getOutreachPerson(item: OutreachItem) {
  return getPerson(item.personId)!;
}
